spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: 1234  
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
